default: &DEFAULT


  weight_init: {conv_init: 'normal', conv_scale: 0.02, conv_bias: 0.}

  lr: 1E-4

  data_path: '/global/cscratch1/sd/jpathak/rbc2d/rbcTrainingSet.h5'
  test_data_path: '/global/cscratch1/sd/jpathak/rbc2d/rbcTestSet.h5'
  ngpu: 1 
  num_epochs: 2
  num_data_workers: 1
  N_out_channels: 5
  batch_size: 1

multi8: 
  <<: *DEFAULT
  ngpu: 8
